name: 'Greeter'
description: 'This action says hello'
author: 'Lance McCarthy'
branding:
  icon: 'box'
  color: 'yellow'
  
outputs:
  greeting:
    description: "The message to be said"
    value: ${{steps.create-greeting.outputs.GREETING}}

runs:
  using: "composite"
  steps:
    - id: say-hello
      shell: bash
      run: |
        word="Hello"
        echo "PARTA=$word" >> "$GITHUB_OUTPUT"

    - id: say-world
      shell: bash
      run: |
        word="World"
        echo "PARTB=$word" >> "$GITHUB_OUTPUT"

    - id: create-greeting
      shell: bash
      run: |
        combinedGreeting="${{steps.say-hello.outputs.PARTA}} ${{steps.say-world.outputs.PARTB}}"
        echo "GREETING=$combinedGreeting" >> "$GITHUB_OUTPUT"