name: Using a Reusable Action

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  say_todays_date:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - id: create-greeting
      uses: ./.github/actions/greeter

    - name: Show Greeting
      run: |
        echo "${{steps.create-greeting.outputs.GREETING}}"
