name: My Main Workflow

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  say_todays_date:
    runs-on: windows-latest
    steps:
    - id: say-hello
      run: |
        $word = "Hello"
        echo "PART=$word" >> "$GITHUB_OUTPUT"

    - id: say-world
      run: |
        $word = "World"
        echo "PART=$word" >> "$GITHUB_OUTPUT"

    - id: create-greeting
      run: |
        $combinedGreeting="${{steps.say-hello.outputs.PART}} ${{steps.say-world.outputs.PART}}"
        echo "GREETING=$combinedGreeting" >> "$GITHUB_OUTPUT"

    - name: Show Greeting
      run: echo "${{steps.create-greeting.outputs.GREETING}}"