name: My Main Workflow

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  say_todays_date:
    runs-on: windows-latest
    steps:
    - id: say-hello
      run: |
        echo "PARTA=$Hello" >> "$GITHUB_OUTPUT"

    - id: say-world
      run: |
        echo "PARTB=World" >> "$GITHUB_OUTPUT"

    - id: create-greeting
      run: |
        $combinedGreeting="${{steps.say-hello.outputs.PARTA}} ${{steps.say-world.outputs.PARTB}}"
        echo "GREETING=$combinedGreeting" >> "$GITHUB_OUTPUT"

    - name: Show Greeting
      run: echo "${{steps.create-greeting.outputs.GREETING}}"