name: My Main Workflow

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  say_todays_date:
    runs-on: windows-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Generate version number using date and run number
      shell: pwsh
      id: version-creator
      run: |
        $buildDay = Get-Date -Format "yyyy.Mdd"
        $ver = $buildDay + "." + $env:GITHUB_RUN_NUMBER + ".0"
        echo "APP_VERSION=$ver" >> $GITHUB_OUTPUT

    - name: Show the date
      run: echo "The date is ${{steps.version-creator.outputs.APP_VERSION}}"`