name: My Main Workflow

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  say_todays_date:
    runs-on: ubuntu-latest
    steps:
    - id: say-hello
      run: |
        word="Hello"
        echo "PARTA=$word" >> "$GITHUB_OUTPUT"

    - id: say-world
      run: |
        word="World"
        echo "PARTB=$word" >> "$GITHUB_OUTPUT"

    - id: create-greeting
      run: |
        combinedGreeting="${{steps.say-hello.outputs.PARTA}} ${{steps.say-world.outputs.PARTB}}"
        echo "GREETING=$combinedGreeting" >> "$GITHUB_OUTPUT"

    - name: Show Greeting
      run: |
        echo "${{steps.create-greeting.outputs.GREETING}}"

    # - name: Set color
    #   id: color-selector
    #   run: echo "SELECTED_COLOR=green" >> "$GITHUB_OUTPUT"

    # - name: Get color
    #   env:
    #     SELECTED_COLOR: ${{ steps.color-selector.outputs.SELECTED_COLOR }}
    #   run: echo "The selected color is $SELECTED_COLOR"